### ISSUE TITLE
代码成功了，但是提问还是超时

### ISSUE THREAD

**Issue by 413162826** [binary-husky/chatgpt_academic#113]
![image](https://user-images.githubusercontent.com/34346573/228584350-c3776df4-ae7e-434f-bccb-06af8a3b9548.png)
![image](https://user-images.githubusercontent.com/34346573/228584415-ff1f7372-3936-48e7-bb2e-ce51ad1a0df5.png)

**Comment by 413162826** [comment]
查询代理的地理位置，返回的结果是{'ip': '104.149.138.137', 'network': '104.149.138.0/23', 'version': 'IPv4', 'city': 'Los Angeles', 'region': 'California', 'region_code': 'CA', 'country': 'US', 'country_name': 'United States', 'country_code': 'US', 'country_code_iso3': 'USA', 'country_capital': 'Washington', 'country_tld': '.us', 'continent_code': 'NA', 'in_eu': False, 'postal': '90017', 'latitude': 34.0515, 'longitude': -118.2707, 'timezone': 'America/Los_Angeles', 'utc_offset': '-0700', 'country_calling_code': '+1', 'currency': 'USD', 'currency_name': 'Dollar', 'languages': 'en-US,es-US,haw,fr', 'country_area': 9629091.0, 'country_population': 327167434, 'asn': 'AS40676', 'org': 'AS40676'}
代理配置 127.0.0.1:17890, 代理所在地：United States
URL http://localhost:9137

Thanks for being a Gradio user! If you have questions or feedback, please join our Discord server and chat with us: https://discord.gg/feTf9x3ZSB
Running on local URL:  http://0.0.0.0:9137
Running on public URL: https://3c776876c9f8f4caa1.gradio.live

This share link expires in 72 hours. For free permanent hosting and GPU upgrades (NEW!), check out Spaces: https://huggingface.co/spaces
 gpt-3.5-turbo : 0 : 你哈
Traceback (most recent call last):
  File "D:\dev\python\lib\site-packages\urllib3\connectionpool.py", line 700, in urlopen
    self._prepare_proxy(conn)
  File "D:\dev\python\lib\site-packages\urllib3\connectionpool.py", line 996, in _prepare_proxy
    conn.connect()
  File "D:\dev\python\lib\site-packages\urllib3\connection.py", line 414, in connect
    self.sock = ssl_wrap_socket(
  File "D:\dev\python\lib\site-packages\urllib3\util\ssl_.py", line 449, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(
  File "D:\dev\python\lib\site-packages\urllib3\util\ssl_.py", line 493, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "D:\dev\python\lib\ssl.py", line 513, in wrap_socket
    return self.sslsocket_class._create(
  File "D:\dev\python\lib\ssl.py", line 1071, in _create
    self.do_handshake()
  File "D:\dev\python\lib\ssl.py", line 1342, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:997)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\dev\python\lib\site-packages\requests\adapters.py", line 489, in send
    resp = conn.urlopen(
  File "D:\dev\python\lib\site-packages\urllib3\connectionpool.py", line 787, in urlopen
    retries = retries.increment(
  File "D:\dev\python\lib\site-packages\urllib3\util\retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/chat/completions (Caused by SSLError(SSLError(1, '[SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:997)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\project\chatgpt_academic\predict.py", line 91, in predict
    response = requests.post(API_URL, headers=headers, proxies=proxies,
  File "D:\dev\python\lib\site-packages\requests\api.py", line 115, in post
    return request("post", url, data=data, json=json, **kwargs)
  File "D:\dev\python\lib\site-packages\requests\api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "D:\dev\python\lib\site-packages\requests\sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "D:\dev\python\lib\site-packages\requests\sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "D:\dev\python\lib\site-packages\requests\adapters.py", line 563, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/chat/completions (Caused by SSLError(SSLError(1, '[SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:997)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\dev\python\lib\site-packages\gradio\routes.py", line 394, in run_predict
    output = await app.get_blocks().process_api(
  File "D:\dev\python\lib\site-packages\gradio\blocks.py", line 1075, in process_api
    result = await self.call_function(
  File "D:\dev\python\lib\site-packages\gradio\blocks.py", line 898, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "D:\dev\python\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "D:\dev\python\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "D:\dev\python\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "D:\dev\python\lib\site-packages\gradio\utils.py", line 549, in async_iteration
    return next(iterator)
  File "D:\project\chatgpt_academic\predict.py", line 98, in predict
    if retry > MAX_RETRY: raise TimeoutError
TimeoutError

**Comment by binary-husky** [comment]
代理配置缺协议 socks5h://localhost:10880。其中socks5h是协议

**Comment by binary-husky** [comment]
代理配置正常，一提交就error #88
