### ISSUE TITLE
解析py文件出错

### ISSUE THREAD

**Issue by Nomination-NRB** [binary-husky/chatgpt_academic#152]
**我的操作**：
![image](https://user-images.githubusercontent.com/83486284/228768962-e982faa3-5519-46cc-83ce-5b0956eecb98.png)

我的**输入参数**为：
![image](https://user-images.githubusercontent.com/83486284/228767871-a0b3a48d-cad2-4b8a-97a1-e0c248fcf8a7.png)

**terminal**：
Traceback (most recent call last):
  File "D:\Python\lib\threading.py", line 932, in _bootstrap_inner
    self.run()
  File "D:\Python\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "D:\git_repository\chatgpt_academic\toolbox.py", line 20, in mt
    mutable[0] = predict_no_ui(inputs=i_say, top_p=top_p, temperature=temperature, history=history, sys_prompt=sys_prompt)
  File "D:\git_repository\chatgpt_academic\predict.py", line 58, in predict_no_ui
    response = requests.post(API_URL, headers=headers, proxies=proxies,
  File "D:\Python\lib\site-packages\requests\api.py", line 115, in post
    return request("post", url, data=data, json=json, **kwargs)
  File "D:\Python\lib\site-packages\requests\api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "D:\Python\lib\site-packages\requests\sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "D:\Python\lib\site-packages\requests\sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "D:\Python\lib\site-packages\requests\adapters.py", line 563, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: SOCKSHTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/chat/completions (Caused by SSLError(SSLCertVerificationError("hostname 'api.openai.com' doesn't match either of 't.co', 'www.t.co'")))
查询代理的地理位置，返回的结果是{'ip': '138.199.21.136', 'network': '138.199.21.0/24', 'version': 'IPv4', 'city': 'Tokyo', 'region': 'Tokyo', 'region_code': 
'13', 'country': 'JP', 'country_name': 'Japan', 'country_code': 'JP', 'country_code_iso3': 'JPN', 'country_capital': 'Tokyo', 'country_tld': '.jp', 'continent_code': 'AS', 'in_eu': False, 'postal': '102-0082', 'latitude': 35.6893, 'longitude': 139.6899, 'timezone': 'Asia/Tokyo', 'utc_offset': '+0900', 'country_calling_code': '+81', 'currency': 'JPY', 'currency_name': 'Yen', 'languages': 'ja', 'country_area': 377835.0, 'country_population': 126529100, 'asn': 'AS212238', 'org': 'Datacamp Limited'}
代理配置 socks5://127.0.0.1:10086, 代理所在地：Japan

**config配置**
![image](https://user-images.githubusercontent.com/83486284/228768477-e77b1c09-26e1-49e3-9fd3-563c346b2b9f.png)

请问我的问题出在哪里了呢，我自己认为会不会是代理不稳定造成的？

**Comment by binary-husky** [comment]
socks5h吧？别socks5  #1

**Comment by binary-husky** [comment]
也可能是http

**Comment by Nomination-NRB** [comment]
> 也可能是http

我将协议全部改成了http了，就正常了，感谢感谢
