### ISSUE TITLE
不需要代理，报错__init__() got an unexpected keyword argument 'ws_max_size'

### ISSUE THREAD

**Issue by YiZhiYuanYuan-qyy** [binary-husky/chatgpt_academic#162]
网络代理状态：未配置。无代理状态下很可能无法访问。
所有问询记录将自动保存在本地目录./gpt_log/chat_secrets.log, 请注意自我隐私保护哦！
查询代理的地理位置，返回的结果是{'error': True, 'reason': 'RateLimited', 'message': 'Visit https://ipapi.co/ratelimited/ for details'}
代理配置 无, 代理所在地：未知，IP查询频率受限
URL http://localhost:65063
Traceback (most recent call last):
  File "/Users/YiZhiYuanYuan/Desktop/chatgpt_academic/main.py", line 113, in <module>
    demo.queue(concurrency_count=CONCURRENT_COUNT).launch(server_name="0.0.0.0", share=True, server_port=PORT, auth=AUTHENTICATION)
  File "/Users/YiZhiYuanYuan/miniforge3/lib/python3.9/site-packages/gradio/blocks.py", line 1454, in launch
    server_name, server_port, local_url, app, server = networking.start_server(
  File "/Users/YiZhiYuanYuan/miniforge3/lib/python3.9/site-packages/gradio/networking.py", line 144, in start_server
    config = uvicorn.Config(
TypeError: __init__() got an unexpected keyword argument 'ws_max_size'

**Comment by YiZhiYuanYuan-qyy** [comment]
是包的版本问题解决啦

**Comment by zzzzzuber** [comment]
> 是包的版本问题解决啦

你好，请问是哪个包的版本导致的呀？我把gradio3.24改成了3.23版本还是有这个错误，麻烦告知一下包名和版本可以吗~
