### ISSUE TITLE
Something went wrong Expecting value: line 1 column 1 (char 0)

### ISSUE THREAD

**Issue by xsl854113598** [binary-husky/chatgpt_academic#2]
在配置好所有文件之后，运行main.py，在弹出的网页中输入，显示Something went wrong Expecting value: line 1 column 1 (char 0)报错，请问是什么原因造成的呀？
![QQ截图20230322164111](https://user-images.githubusercontent.com/92251564/226847375-3f5f8a7b-f95d-405e-b9c1-3a785edb764b.jpg)

**Comment by xsl854113598** [comment]
您好，非常不好意思，我是个初学者。。我想请问一下您说的命令行的输出在哪里看，是需要打开哪个文件给您截图呢?

**Comment by binary-husky** [comment]
应该代理软件设置出了问题，连127.0.0.1都接管了，调整代理软件的设置，如果不行，最暴力的方法是把windows系统设置的代理关闭即可：
![image](https://user-images.githubusercontent.com/96192199/226874319-4320d41b-01db-4884-abd1-3bb5372eb4de.png)

**Comment by xsl854113598** [comment]
您好，我看到了您在这里和在B站给我的回复，我本来想在B站和您交流，但是涉及到一些梯子的事情，所以在这里和您说一下，我用的是clash，里面好像没有直接选择绕开局域网和大陆的选项，我刚刚尝试调整了一下，好像不是很行。然后您在这里说的方式我也尝试了一下，把
![QQ截图20230322190003](https://user-images.githubusercontent.com/92251564/226884089-bb099897-153c-4c7c-a848-0bfc98faf2e9.jpg)
windows系统设置的代理关闭后，程序没有之前的报错了，但是直接显示了Request timeout, network error. please check proxy settings in config.py.，和下图所示的一样

**Comment by xsl854113598** [comment]
py.exe里显示的是这样的

**Comment by xsl854113598** [comment]
网络代理状态：运行。
URL http://localhost:13749
Running on local URL:  http://0.0.0.0:13749
chat_counter - 0
Traceback (most recent call last):
  File "C:\Users\XSL\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "C:\Users\XSL\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\connectionpool.py", line 1042, in _validate_conn
    conn.connect()
  File "C:\Users\XSL\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\connection.py", line 419, in connect
    self.sock = ssl_wrap_socket(
  File "C:\Users\XSL\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\util\ssl_.py", line 449, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(
  File "C:\Users\XSL\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\util\ssl_.py", line 493, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)  File "C:\Users\XSL\AppData\Local\Programs\Python\Python39\lib\ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "C:\Users\XSL\AppData\Local\Programs\Python\Python39\lib\ssl.py", line 1040, in _create
    self.do_handshake()
  File "C:\Users\XSL\AppData\Local\Programs\Python\Python39\lib\ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
socket.timeout: _ssl.c:1112: The handshake operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\XSL\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\adapters.py", line 489, in send
    resp = conn.urlopen(
  File "C:\Users\XSL\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\connectionpool.py", line 787, in urlopen
    retries = retries.increment(
  File "C:\Users\XSL\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\util\retry.py", line 550, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "C:\Users\XSL\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\packages\six.py", line 770, in reraise
    raise value
  File "C:\Users\XSL\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "C:\Users\XSL\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\connectionpool.py", line 389, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=conn.timeout)
  File "C:\Users\XSL\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\connectionpool.py", line 340, in _raise_timeout
    raise ReadTimeoutError(
urllib3.exceptions.ReadTimeoutError: SOCKSHTTPSConnectionPool(host='api.openai.com', port=443): Read timed out. (read timeout=15)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\XSL\Downloads\chatgpt_academic-master\predict.py", line 89, in predict
    response = requests.post(API_URL, headers=headers, proxies=proxies,
  File "C:\Users\XSL\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\api.py", line 115, in post
    return request("post", url, data=data, json=json, **kwargs)
  File "C:\Users\XSL\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Users\XSL\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\XSL\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\XSL\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\adapters.py", line 578, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: SOCKSHTTPSConnectionPool(host='api.openai.com', port=443): Read timed out. (read timeout=15)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\XSL\AppData\Local\Programs\Python\Python39\lib\site-packages\gradio\routes.py", line 394, in run_predict
    output = await app.get_blocks().process_api(
  File "C:\Users\XSL\AppData\Local\Programs\Python\Python39\lib\site-packages\gradio\blocks.py", line 1075, in process_api
    result = await self.call_function(
  File "C:\Users\XSL\AppData\Local\Programs\Python\Python39\lib\site-packages\gradio\blocks.py", line 898, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "C:\Users\XSL\AppData\Local\Programs\Python\Python39\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "C:\Users\XSL\AppData\Local\Programs\Python\Python39\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread    return await future
  File "C:\Users\XSL\AppData\Local\Programs\Python\Python39\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "C:\Users\XSL\AppData\Local\Programs\Python\Python39\lib\site-packages\gradio\utils.py", line 549, in async_iteration
    return next(iterator)
  File "C:\Users\XSL\Downloads\chatgpt_academic-master\predict.py", line 94, in predict
    raise TimeoutError
TimeoutError

**Comment by binary-husky** [comment]
@xsl854113598 更新一下代码吧，我刚修复了一下代理环境的问题，有些人系统里确实存在这个问题

**Comment by binary-husky** [comment]
> @xsl854113598 更新一下代码吧，我刚修复了一下代理环境的问题，有些人系统里确实存在这个问题

如果还不行的话，贴一下 下面这个命令的输出
```
python check_proxy.py
```

**Comment by xsl854113598** [comment]
好的好的，感谢您
