### ISSUE TITLE
解析错误，各位大佬是否遇到过？？？？

### ISSUE THREAD

**Issue by MengLiu999** [binary-husky/chatgpt_academic#223]
[Local Message] Json Error

Traceback (most recent call last):

File "/Users/liuman/chatgpt_academic/predict.py", line 163, in predict

if len(json.loads(chunk.decode()[6:])['choices'][0]["delta"]) == 0:
File "/Users/liuman/opt/anaconda3/lib/python3.9/json/init.py", line 346, in loads

return _default_decoder.decode(s)
File "/Users/liuman/opt/anaconda3/lib/python3.9/json/decoder.py", line 337, in decode

obj, end = self.raw_decode(s, idx=_w(s, 0).end())
File "/Users/liuman/opt/anaconda3/lib/python3.9/json/decoder.py", line 355, in raw_decode

raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

"error": { "message": "You exceeded your current quota, please check your plan and billing details.", "type": "insufficient_quota", "param": null, "code": null }}

**Comment by Ultrasty** [comment]
看最后一行：You exceeded your current quota, please check your plan and billing details.
API的免费额度用完或者过期了

**Comment by binary-husky** [comment]
额度不足，或者额度没用完但是过期了#263

**Comment by binary-husky** [comment]
额度不足，或者额度没用完但是过期了  #263 #227
