### ISSUE TITLE
运行main.py 报错：TypeError: Expected maxsize to be an integer or None

### ISSUE THREAD

**Issue by EthanCodesss** [binary-husky/chatgpt_academic#234]
完整报错信息为：
Traceback (most recent call last):
  File "main.py", line 3, in <module>
    from predict import predict
  File "D:\software\chatgpt_academic\predict.py", line 23, in <module>
    from toolbox import get_conf
  File "D:\software\chatgpt_academic\toolbox.py", line 292, in <module>
    @lru_cache
  File "D:\software\python\lib\functools.py", line 490, in lru_cache
    raise TypeError('Expected maxsize to be an integer or None')
TypeError: Expected maxsize to be an integer or None

config.py也配置好了，不知道哪里出错，感谢！

**Comment by binary-husky** [comment]
python 版本？

**Comment by EthanCodesss** [comment]
> python 版本？

3.7.9

**Comment by fulyaec** [comment]
改成@lru_cache(128)就可以了

**Comment by binary-husky** [comment]
已经紧急修复

**Comment by EthanCodesss** [comment]
> 改成@lru_cache(128)就可以了

感谢

**Comment by EthanCodesss** [comment]
> 已经紧急修复

感谢
