### ISSUE TITLE
Json Error

### ISSUE THREAD

**Issue by Sandwiches97** [binary-husky/chatgpt_academic#263]
提交之后，错误信息如下，请问这是什么原因呢？

[Local Message] Json Error

Traceback (most recent call last):

File "C:\Users\Aurora_c\OneDrive\桌面\git\chatgpt_academic\predict.py", line 163, in predict

if len(json.loads(chunk.decode()[6:])['choices'][0]["delta"]) == 0:
File "A:\Conda\envs\gpt\lib\json__init__.py", line 348, in loads

return _default_decoder.decode(s)
File "A:\Conda\envs\gpt\lib\json\decoder.py", line 337, in decode

obj, end = self.raw_decode(s, idx=_w(s, 0).end())
File "A:\Conda\envs\gpt\lib\json\decoder.py", line 355, in raw_decode

raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

"error": { "message": "You exceeded your current quota, please check your plan and billing details.", "type": "insufficient_quota", "param": null, "code": null }}

**Comment by dxh8286239** [comment]
me too，how did fix it？

**Comment by binary-husky** [comment]
这问题找OpenAI啊：

![image](https://user-images.githubusercontent.com/96192199/229342935-b82d5306-c0f7-4420-90be-de03ced83a85.png)
