### ISSUE TITLE
error Python、

### ISSUE THREAD

**Issue by njuxyh** [binary-husky/chatgpt_academic#273]
Traceback (most recent call last):
  File "C:\Users\Administrator\Downloads\Compressed\chatgpt_academic-master\predict.py", line 169, in predict
    if len(json.loads(chunk.decode()[6:])['choices'][0]["delta"]) == 0:
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\anaconda3\envs\gptac_venv\Lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\anaconda3\envs\gptac_venv\Lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\anaconda3\envs\gptac_venv\Lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "C:\Users\Administrator\Downloads\Compressed\chatgpt_academic-master\predict.py", line 169, in predict
    if len(json.loads(chunk.decode()[6:])['choices'][0]["delta"]) == 0:
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\anaconda3\envs\gptac_venv\Lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\anaconda3\envs\gptac_venv\Lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\anaconda3\envs\gptac_venv\Lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by 2698022795** [comment]
[Local Message] Json Error

Traceback (most recent call last):

File "D:\study\学习工具\chatgpt_academic\predict.py", line 163, in predict

if len(json.loads(chunk.decode()[6:])['choices'][0]["delta"]) == 0:
File "D:\software\anaconda\envs\chatgpt_academic\lib\json__init__.py", line 346, in loads

return _default_decoder.decode(s)
File "D:\software\anaconda\envs\chatgpt_academic\lib\json\decoder.py", line 337, in decode

obj, end = self.raw_decode(s, idx=_w(s, 0).end())
File "D:\software\anaconda\envs\chatgpt_academic\lib\json\decoder.py", line 355, in raw_decode

raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

"error": { "message": "You exceeded your current quota, please check your plan and billing details.", "type": "insufficient_quota", "param": null, "code": null }}

**Comment by zeduth** [comment]
[Local Message] Json Error

Traceback (most recent call last):

File "D:\chromedowload\chatgpt_academic-master (2)\chatgpt_academic-master\predict.py", line 162, in predict

if len(json.loads(chunk.decode()[6:])['choices'][0]["delta"]) == 0:
File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\json__init__.py", line 346, in loads

return _default_decoder.decode(s)
File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\json\decoder.py", line 337, in decode

obj, end = self.raw_decode(s, idx=_w(s, 0).end())
File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\json\decoder.py", line 355, in raw_decode

raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

ead>
Access denied
You do not have access to chat.openai.com.

The site owner may have set restrictions that prevent you from accessing the site.

Ray ID: 7b1f4b5089bace48
Timestamp: 2023-04-03 06:35:54 UTC
Your IP address: 150.230.45.108
Requested URL: chat.openai.com/backend-api/conversation
Error reference number: 1020
Server ID: FL_466F7
User-Agent: python-requests/2.28.2


[Local Message] Json Error

Traceback (most recent call last):

File "D:\chromedowload\chatgpt_academic-master (2)\chatgpt_academic-master\predict.py", line 162, in predict

if len(json.loads(chunk.decode()[6:])['choices'][0]["delta"]) == 0:
File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\json__init__.py", line 346, in loads

return _default_decoder.decode(s)
File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\json\decoder.py", line 337, in decode

obj, end = self.raw_decode(s, idx=_w(s, 0).end())
File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\json\decoder.py", line 355, in raw_decode

raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

ead>
Access denied
You do not have access to chat.openai.com.

The site owner may have set restrictions that prevent you from accessing the site.

Ray ID: 7b1f4b5089bace48
Timestamp: 2023-04-03 06:35:54 UTC
Your IP address: 150.230.45.108
Requested URL: chat.openai.com/backend-api/conversation
Error reference number: 1020
Server ID: FL_466F7
User-Agent: python-requests/2.28.2

**Comment by binary-husky** [comment]
更新代码，有的是账号余额过期了，有的是账号失效
