### ISSUE TITLE
GPT-4 APIkey is out, can you support it now? GPT-4 APIkey已出，请问可以支持了吗？

### ISSUE THREAD

**Issue by tianyu-z** [binary-husky/chatgpt_academic#276]
GPT-4 APIkey is out, can you support it now?

**Comment by binary-husky** [comment]
我们没有gpt4的key

请在config里面把模型改成 gpt-4，如果有报错，把报错信息发一下

**Comment by ashEsto475** [comment]
> 我们没有gpt4的key
> 
> 请在config里面把模型改成 gpt-4，如果有报错，把报错信息发一下

"error": { "message": "The model: gpt-4 does not exist", "type": "invalid_request_error", "param": null, "code": "model_not_found" }}

我得到了这个. gpt4的model名称好像不叫gpt-4？

**Comment by hklz** [comment]
[Local Message] Json Error

Traceback (most recent call last):

File "E:\software\chatgpt_academic-master\predict.py", line 114, in predict

if len(json.loads(chunk.decode()[6:])['choices'][0]["delta"]) == 0:
File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\json__init__.py", line 346, in loads

return _default_decoder.decode(s)
File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\json\decoder.py", line 337, in decode

obj, end = self.raw_decode(s, idx=_w(s, 0).end())
File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\json\decoder.py", line 355, in raw_decode

raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

"error": { "message": "The model: gpt-4 does not exist", "type": "invalid_request_error", "param": null, "code": "model_not_found" }}
