### ISSUE TITLE
 [感谢]请问可否提供一份全英文的本项目源代码？自己运行后出错

### ISSUE THREAD

**Issue by longfuxu** [binary-husky/chatgpt_academic#300]
**Describe the bug 简述**
请问可否提供一份全英文的本项目源代码？自己运行后出错
**Screen Shot 截图**
![image](https://user-images.githubusercontent.com/62403015/229631929-d5ba0eb0-8cd9-4838-8633-1c475f8569bb.png)

![image](https://user-images.githubusercontent.com/62403015/229630757-f68d6545-d371-43c2-a3c6-c17d43df3ed4.png)

**Terminal Traceback 终端traceback（如果有）**
Traceback (most recent call last):
  File "/Users/longfu/.pyenv/versions/3.10.6/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/Users/longfu/.pyenv/versions/3.10.6/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/longfu/OpenAI Projects/chatgpt_academic/crazy_functions/代码重写为全英文_多线程.py", line 35, in thread_worker
    gpt_say = predict_no_ui_long_connection(inputs=i_say, top_p=top_p, temperature=temperature, history=history, sys_prompt=sys_prompt)
  File "/Users/longfu/OpenAI Projects/chatgpt_academic/predict.py", line 111, in predict_no_ui_long_connection
    raise ConnectionAbortedError("正常结束，但显示Token不足。")
ConnectionAbortedError: 正常结束，但显示Token不足。
 chatbot, history, msg

查询代理的地理位置，返回的结果是{'error': True, 'reason': 'RateLimited', 'message': 'Visit https://ipapi.co/ratelimited/ for details'}
代理配置 无, 代理所在地：未知，IP查询频率受限

我自己绑定信用卡，不会余额不足，其他应用仍然可以使用，不知道什么原因。
如果您那边可以运行，可否提供一个branch，谢谢大佬

**Comment by binary-husky** [comment]
更新pytohn版本

**Comment by binary-husky** [comment]
文本的长度恰好卡了一个临界值附近，导致openai没法返回输出文本……

**Comment by longfuxu** [comment]
谢谢
