### ISSUE TITLE
打开浏览器一直loading

### ISSUE THREAD

**Issue by xuyang-C** [binary-husky/chatgpt_academic#306]
提示代理配置成功了，但是打开浏览器后一直loading

**Comment by xuyang-C** [comment]
Running on local URL:  http://0.0.0.0:18364
Traceback (most recent call last):
  File "D:\Googlechrome_download\chatgpt_academic-master\main.py", line 147, in <module>
    demo.queue(concurrency_count=CONCURRENT_COUNT).launch(server_name="0.0.0.0", share=True, server_port=PORT, auth=AUTHENTICATION)
  File "C:\Users\xuyangchen\.conda\envs\gptac_venv\Lib\site-packages\gradio\blocks.py", line 1600, in launch
    self.share_url = networking.setup_tunnel(
                     ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xuyangchen\.conda\envs\gptac_venv\Lib\site-packages\gradio\networking.py", line 168, in setup_tunnel
    address = tunnel.start_tunnel()
              ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xuyangchen\.conda\envs\gptac_venv\Lib\site-packages\gradio\tunneling.py", line 61, in start_tunnel
    self.url = self._start_tunnel(binary_path)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xuyangchen\.conda\envs\gptac_venv\Lib\site-packages\gradio\tunneling.py", line 97, in _start_tunnel
    line = self.proc.stdout.readline()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyboardInterrupt
Killing tunnel 0.0.0.0:18364 <> None

应该是卡在这里

**Comment by charmy20** [comment]
我也是一直Loading

**Comment by crankler** [comment]
请问你们怎么解决的呀
