### ISSUE TITLE
[Local Message] Json Error

### ISSUE THREAD

**Issue by czhcooper** [binary-husky/chatgpt_academic#31]
After running python main.py,  the proxy is fine.  When typing questions on the web app, it returns this:

[Local Message] Json Error

Traceback (most recent call last):

File "/Users/cooper/Documents/chatgpt_academic/predict.py", line 114, in predict

if len(json.loads(chunk.decode()[6:])['choices'][0]["delta"]) == 0:
File "/Users/cooper/opt/anaconda3/lib/python3.9/json/init.py", line 346, in loads

return _default_decoder.decode(s)
File "/Users/cooper/opt/anaconda3/lib/python3.9/json/decoder.py", line 337, in decode

obj, end = self.raw_decode(s, idx=_w(s, 0).end())
File "/Users/cooper/opt/anaconda3/lib/python3.9/json/decoder.py", line 355, in raw_decode

raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

"error": { "message": "You exceeded your current quota, please check your plan and billing details.", "type": "insufficient_quota", "param": null, "code": null }}  

What is going on there?

**Comment by binary-husky** [comment]
最后一句已经告诉你了呀，额度用完该给openai充money了
You exceeded your current quota, please check your plan and billing details.

**Comment by czhcooper** [comment]
好的，我在gpt官网上一直免费的，没想到API要收费 [Lol]
