### ISSUE TITLE
ImportError: cannot import name dataclass_transform

### ISSUE THREAD

**Issue by Popantelope** [binary-husky/chatgpt_academic#332]
运行python main.py时报错

Traceback (most recent call last):
  File "main.py", line 2, in <module>
    import gradio as gr
  File "D:\Anaconda3\lib\site-packages\gradio\__init__.py", line 3, in <module>
    import gradio.components as components
  File "D:\Anaconda3\lib\site-packages\gradio\components.py", line 32, in <module>
    from fastapi import UploadFile
  File "D:\Anaconda3\lib\site-packages\fastapi\__init__.py", line 7, in <module>
    from .applications import FastAPI as FastAPI
  File "D:\Anaconda3\lib\site-packages\fastapi\applications.py", line 16, in <module>
    from fastapi import routing
  File "D:\Anaconda3\lib\site-packages\fastapi\routing.py", line 22, in <module>
    from fastapi import params
  File "D:\Anaconda3\lib\site-packages\fastapi\params.py", line 4, in <module>
    from pydantic.fields import FieldInfo, Undefined
  File "pydantic\__init__.py", line 2, in init pydantic.__init__
  File "pydantic\dataclasses.py", line 41, in init pydantic.dataclasses
    # +---------+-----------------------------------------+
ImportError: cannot import name dataclass_transform
![image](https://user-images.githubusercontent.com/76279091/230123544-c93a1302-1b7e-47b6-b2f8-a89bfc6f3be0.png)

请问有大神知道怎么解决这个问题吗

**Comment by binary-husky** [comment]
严格按照readme的anaconda流程走

**Comment by lee376** [comment]
兄弟，我在使用gradio的时候也遇到了这个问题，你现在解决了吗？

**Comment by Popantelope** [comment]
> 
重装一边fastapi解决了
pip uninstall fastapi
pip install fastapi
