### ISSUE TITLE
批量翻译PDF报错"存在一行极长的文本！"

### ISSUE THREAD

**Issue by wlp233** [binary-husky/chatgpt_academic#349]
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\chatgpt_academic-master-4.0\crazy_functions\crazy_utils.py", line 146, in breakdown_txt_to_satisfy_token_limit_for_pdf
    return cut(txt, must_break_at_empty_line=True)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\Desktop\chatgpt_academic-master-lab2.0\crazy_functions\crazy_utils.py", line 139, in cut
    raise RuntimeError("存在一行极长的文本！")
RuntimeError: 存在一行极长的文本！

**Comment by wlp233** [comment]
![image](https://user-images.githubusercontent.com/73226302/230401021-b7fa9ac5-bcb4-4720-9e9e-05b69f17098c.png)
是不是没翻译完就停止了？

**Comment by binary-husky** [comment]
traceback不太完整，测试样本方便分享吗？

**Comment by wlp233** [comment]
可以的，随手拿了篇论文测试
[1-s2.0-S0009261400012707-main.pdf](https://github.com/binary-husky/chatgpt_academic/files/11172488/1-s2.0-S0009261400012707-main.pdf)

**Comment by binary-husky** [comment]
这个pdf似乎有点特殊

![image](https://user-images.githubusercontent.com/96192199/230522954-8e54b335-ab9d-4ad1-83fb-7bbcdd1282ad.png)

**Comment by binary-husky** [comment]
https://github.com/pymupdf/PyMuPDF/issues/501
pdf可能有混淆措施
