### ISSUE TITLE
翻译PDF时出现编码错误

### ISSUE THREAD

**Issue by siran-CN** [binary-husky/chatgpt_academic#351]
**Describe the bug 简述**
翻译到中途进程停止，出现错误如下：

```
[Local Message] 实验性函数调用出错:

Traceback (most recent call last):
  File "D:\Git Projects\chatgpt_academic\toolbox.py", line 149, in decorated
    yield from f(txt, top_p, temperature, chatbot, history, systemPromptTxt, WEB_PORT)
  File "D:\Git Projects\chatgpt_academic\crazy_functions\批量翻译PDF文档_多线程.py", line 138, in 批量翻译PDF文档
    yield from 解析PDF(file_manifest, project_folder, top_p, temperature, chatbot, history, sys_prompt)
  File "D:\Git Projects\chatgpt_academic\crazy_functions\批量翻译PDF文档_多线程.py", line 170, in 解析PDF
    gpt_response_collection = yield from request_gpt_model_multi_threads_with_very_awesome_ui_and_high_efficiency(
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Git Projects\chatgpt_academic\crazy_functions\crazy_utils.py", line 83, in request_gpt_model_multi_threads_with_very_awesome_ui_and_high_efficiency
    gpt_res = f.result()
              ^^^^^^^^^^
  File "D:\Python\Python311\Lib\concurrent\futures\_base.py", line 449, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "D:\Python\Python311\Lib\concurrent\futures\_base.py", line 401, in __get_result
    raise self._exception
  File "D:\Python\Python311\Lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Git Projects\chatgpt_academic\crazy_functions\crazy_utils.py", line 46, in _req_gpt
    gpt_say = predict_no_ui_long_connection(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Git Projects\chatgpt_academic\request_llm\bridge_chatgpt.py", line 90, in predict_no_ui_long_connection
    headers, payload = generate_payload(inputs, top_p, temperature, history, system_prompt=sys_prompt, stream=True)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Git Projects\chatgpt_academic\request_llm\bridge_chatgpt.py", line 265, in generate_payload
    print(f" {LLM_MODEL} : {conversation_cnt} : {inputs}")
UnicodeEncodeError: 'gbk' codec can't encode character '\ufb01' in position 156: illegal multibyte sequence
```

我是在2.4更新后才开始使用这个项目的，版本应该没有问题。

**Comment by binary-husky** [comment]
也许是PDF的编码问题？ 测试样本方便分享吗？

**Comment by siran-CN** [comment]
[20110011143.pdf](https://github.com/binary-husky/chatgpt_academic/files/11175052/20110011143.pdf)
好的，这篇论文在 https://ntrs.nasa.gov/citations/20110011143 也可以下载。

**Comment by siran-CN** [comment]
我又尝试翻译了两篇论文，均出现了类似的报错，这里一起附上来了，希望可以帮到你们：

[Implementation of Acoustic Materials to the VLS-1 Fairing - A Sensitivity Analysis Using SEA.pdf](https://github.com/binary-husky/chatgpt_academic/files/11175088/Implementation.of.Acoustic.Materials.to.the.VLS-1.Fairing.-.A.Sensitivity.Analysis.Using.SEA.pdf)

```
 [Local Message] 实验性函数调用出错:

Traceback (most recent call last):
  File "D:\Git Projects\chatgpt_academic\toolbox.py", line 149, in decorated
    yield from f(txt, top_p, temperature, chatbot, history, systemPromptTxt, WEB_PORT)
  File "D:\Git Projects\chatgpt_academic\crazy_functions\批量翻译PDF文档_多线程.py", line 138, in 批量翻译PDF文档
    yield from 解析PDF(file_manifest, project_folder, top_p, temperature, chatbot, history, sys_prompt)
  File "D:\Git Projects\chatgpt_academic\crazy_functions\批量翻译PDF文档_多线程.py", line 162, in 解析PDF
    paper_meta_info = yield from request_gpt_model_in_new_thread_with_ui_alive(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Git Projects\chatgpt_academic\crazy_functions\crazy_utils.py", line 27, in request_gpt_model_in_new_thread_with_ui_alive
    return future.result()
           ^^^^^^^^^^^^^^^
  File "D:\Python\Python311\Lib\concurrent\futures\_base.py", line 449, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "D:\Python\Python311\Lib\concurrent\futures\_base.py", line 401, in __get_result
    raise self._exception
  File "D:\Python\Python311\Lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Git Projects\chatgpt_academic\crazy_functions\crazy_utils.py", line 14, in <lambda>
    predict_no_ui_long_connection(
  File "D:\Git Projects\chatgpt_academic\request_llm\bridge_chatgpt.py", line 90, in predict_no_ui_long_connection
    headers, payload = generate_payload(inputs, top_p, temperature, history, system_prompt=sys_prompt, stream=True)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Git Projects\chatgpt_academic\request_llm\bridge_chatgpt.py", line 265, in generate_payload
    print(f" {LLM_MODEL} : {conversation_cnt} : {inputs}")
UnicodeEncodeError: 'gbk' codec can't encode character '\xe3' in position 330: illegal multibyte sequence
```

[Fairing Noise Control Using Tube-shaped Resonators.pdf](https://github.com/binary-husky/chatgpt_academic/files/11175099/Fairing.Noise.Control.Using.Tube-shaped.Resonators.pdf)

```
[Local Message] 实验性函数调用出错:

Traceback (most recent call last):
  File "D:\Git Projects\chatgpt_academic\toolbox.py", line 149, in decorated
    yield from f(txt, top_p, temperature, chatbot, history, systemPromptTxt, WEB_PORT)
  File "D:\Git Projects\chatgpt_academic\crazy_functions\批量翻译PDF文档_多线程.py", line 138, in 批量翻译PDF文档
    yield from 解析PDF(file_manifest, project_folder, top_p, temperature, chatbot, history, sys_prompt)
  File "D:\Git Projects\chatgpt_academic\crazy_functions\批量翻译PDF文档_多线程.py", line 170, in 解析PDF
    gpt_response_collection = yield from request_gpt_model_multi_threads_with_very_awesome_ui_and_high_efficiency(
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Git Projects\chatgpt_academic\crazy_functions\crazy_utils.py", line 83, in request_gpt_model_multi_threads_with_very_awesome_ui_and_high_efficiency
    gpt_res = f.result()
              ^^^^^^^^^^
  File "D:\Python\Python311\Lib\concurrent\futures\_base.py", line 449, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "D:\Python\Python311\Lib\concurrent\futures\_base.py", line 401, in __get_result
    raise self._exception
  File "D:\Python\Python311\Lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Git Projects\chatgpt_academic\crazy_functions\crazy_utils.py", line 46, in _req_gpt
    gpt_say = predict_no_ui_long_connection(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Git Projects\chatgpt_academic\request_llm\bridge_chatgpt.py", line 90, in predict_no_ui_long_connection
    headers, payload = generate_payload(inputs, top_p, temperature, history, system_prompt=sys_prompt, stream=True)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Git Projects\chatgpt_academic\request_llm\bridge_chatgpt.py", line 265, in generate_payload
    print(f" {LLM_MODEL} : {conversation_cnt} : {inputs}")
UnicodeEncodeError: 'gbk' codec can't encode character '\xbd' in position 1025: illegal multibyte sequence
```

**Comment by binary-husky** [comment]
无法复现，这个在你电脑上的输出是？
```
python -c "import sys; print(sys.stdout.encoding)"
```

**Comment by siran-CN** [comment]
输出是 utf-8

**Comment by siran-CN** [comment]
2.5更新后翻译不报错了，使用体验极佳，感谢大佬们的辛苦努力！

**Comment by marshzhao** [comment]
我使用”批量翻译PDF文档时“遇到了相同的问题：UnicodeEncodeError: 'gbk' codec can't encode character '\xb4' in position 259: illegal multibyte sequence。即使时更新2.5也出现。

**Comment by binary-husky** [comment]
定位的问题是终端的编码是gbk的缘故，临时的解决方式是不用git bash换成powershell或者其他更亲近windows的终端。

**Comment by Gilgameshzhangqihang** [comment]
[Local Message] 实验性函数调用出错:

Traceback (most recent call last):
  File ".\toolbox.py", line 88, in decorated
    yield from f(txt, top_p, temperature, chatbot, history, systemPromptTxt, WEB_PORT)
  File ".\crazy_functions\批量翻译PDF文档_多线程.py", line 56, in 批量翻译PDF文档
    yield from 解析PDF(file_manifest, project_folder, llm_kwargs, plugin_kwargs, chatbot, history, sys_prompt)
  File ".\crazy_functions\批量翻译PDF文档_多线程.py", line 113, in 解析PDF
    res = write_results_to_file(final, file_name=create_report_file_name)
  File ".\toolbox.py", line 168, in write_results_to_file
    with open(f'./gpt_log/{file_name}', 'w', encoding='utf8') as f:
FileNotFoundError: [Errno 2] No such file or directory: './gpt_log/[Journal of Transportation Engineering, Part B_ Pavements 2021-mar vol. 147 iss. 1] Qian, Jinsong_ Chen, Xinran_ Ling, Jianming_ Li, Jiayang - Estimating the Contribution of Suction on the Resilient Modulus of Subgr.pdf.trans.md'
请问这是怎么回事

**Comment by Gilgameshzhangqihang** [comment]
代理所在地：未知，IP查询频率受限，
现在就这样了
