### ISSUE TITLE
批量翻译PDF文档时出现UnicodeEncodeError

### ISSUE THREAD

**Issue by marshzhao** [binary-husky/chatgpt_academic#398]
论文名称：causal mediation analysis with double machine learning

请从private_upload/2023-04-10-12-15-40\causal mediation analysis with double machine learning.pdf中提取出“标题”、“收录会议或期刊”等基本信息。

[Local Message] 实验性函数调用出错:

Traceback (most recent call last):
  File "C:\Users\Administrator\chatgpt_academic\toolbox.py", line 149, in decorated
    yield from f(txt, top_p, temperature, chatbot, history, systemPromptTxt, WEB_PORT)
  File "C:\Users\Administrator\chatgpt_academic\crazy_functions\批量翻译PDF文档_多线程.py", line 138, in 批量翻译PDF文档
    yield from 解析PDF(file_manifest, project_folder, top_p, temperature, chatbot, history, sys_prompt)
  File "C:\Users\Administrator\chatgpt_academic\crazy_functions\批量翻译PDF文档_多线程.py", line 162, in 解析PDF
    paper_meta_info = yield from request_gpt_model_in_new_thread_with_ui_alive(
  File "C:\Users\Administrator\chatgpt_academic\crazy_functions\crazy_utils.py", line 27, in request_gpt_model_in_new_thread_with_ui_alive
    return future.result()
  File "C:\Program Files\python\lib\concurrent\futures\_base.py", line 432, in result
    return self.__get_result()
  File "C:\Program Files\python\lib\concurrent\futures\_base.py", line 388, in __get_result
    raise self._exception
  File "C:\Program Files\python\lib\concurrent\futures\thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\Users\Administrator\chatgpt_academic\crazy_functions\crazy_utils.py", line 14, in <lambda>
    predict_no_ui_long_connection(
  File "C:\Users\Administrator\chatgpt_academic\request_llm\bridge_chatgpt.py", line 90, in predict_no_ui_long_connection
    headers, payload = generate_payload(inputs, top_p, temperature, history, system_prompt=sys_prompt, stream=True)
  File "C:\Users\Administrator\chatgpt_academic\request_llm\bridge_chatgpt.py", line 268, in generate_payload
    print(f" {LLM_MODEL} : {conversation_cnt} : {inputs}")
UnicodeEncodeError: 'gbk' codec can't encode character '\xb4' in position 259: illegal multibyte sequence

**Comment by marshzhao** [comment]
忘记论文原始下载地址了，如何把论文发送到您的邮箱？

**Comment by marshzhao** [comment]
python -c "import sys; print(sys.stdout.encoding)"
gbk

**Comment by binary-husky** [comment]
是公开论文吗，公开的话在这上传附件就行

**Comment by binary-husky** [comment]
似乎是编码问题，我不能理解它为啥会在print时报错😂

**Comment by binary-husky** [comment]
https://github.com/Microsoft/vscode/issues/6269
也许是终端的问题，请问你用的是什么终端呢？还有windows版本？

**Comment by marshzhao** [comment]
Windows 10 教育版 64位系统
git version 2.40.0.windows.1

这是翻译出错的论文。
[causal mediation analysis with double machine learning.pdf](https://github.com/binary-husky/chatgpt_academic/files/11190388/causal.mediation.analysis.with.double.machine.learning.pdf)

**Comment by binary-husky** [comment]
好的 我们试验一下

**Comment by binary-husky** [comment]
@marshzhao #351
定位的问题是终端的编码是gbk的缘故，临时的解决方式是不用git bash换成powershell或者其他更亲近windows的终端。

**Comment by marshzhao** [comment]
谢谢您！
