### ISSUE TITLE
chatbot中只有提问，没有回复，这正常嘛？TypeError: write() argument must be str, not None

### ISSUE THREAD

**Issue by something-19** [binary-husky/chatgpt_academic#42]
<img width="598" alt="1679999228466" src="https://user-images.githubusercontent.com/104243312/228207900-d86e3011-223a-4b01-b943-5173c70b94c6.png">

**Comment by something-19** [comment]
> 不正常，没见过这种情况。终端的traceback有吗

```
 gpt-3.5-turbo : 8 : 根据以上你自己的分析，对程序的整体功能和构架做出概括。然后用一张markdown表格整理每个文件的功能（包括['check_proxy.py', 'config.py', 'functional.py', 'functional_crazy.py', 'main.py', 'predict.py', 'show_math.py', 'toolbox.py']）。
Exception in thread Thread-21:
Traceback (most recent call last):
  File "C:\anaconda3\lib\threading.py", line 980, in _bootstrap_inner
    self.run()
  File "C:\anaconda3\lib\threading.py", line 917, in run
    self._target(*self._args, **self._kwargs)
  File "D:\GitStore\Fork_chatgpt_academic\toolbox.py", line 20, in mt
    mutable[0] = predict_no_ui(inputs=i_say, top_p=top_p, temperature=temperature, history=history)
  File "D:\GitStore\Fork_chatgpt_academic\predict.py", line 45, in predict_no_ui
    response = requests.post(API_URL, headers=headers, proxies=proxies,
  File "D:\GitStore\Fork_chatgpt_academic\venv\lib\site-packages\requests\api.py", line 115, in post
    return request("post", url, data=data, json=json, **kwargs)
  File "D:\GitStore\Fork_chatgpt_academic\venv\lib\site-packages\requests\api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "D:\GitStore\Fork_chatgpt_academic\venv\lib\site-packages\requests\sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "D:\GitStore\Fork_chatgpt_academic\venv\lib\site-packages\requests\sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "D:\GitStore\Fork_chatgpt_academic\venv\lib\site-packages\requests\adapters.py", line 489, in send
    resp = conn.urlopen(
  File "D:\GitStore\Fork_chatgpt_academic\venv\lib\site-packages\urllib3\connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "D:\GitStore\Fork_chatgpt_academic\venv\lib\site-packages\urllib3\connectionpool.py", line 398, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "D:\GitStore\Fork_chatgpt_academic\venv\lib\site-packages\urllib3\connection.py", line 244, in request
    super(HTTPConnection, self).request(method, url, body=body, headers=headers)
  File "C:\anaconda3\lib\http\client.py", line 1285, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "C:\anaconda3\lib\http\client.py", line 1326, in _send_request
    self.putheader(hdr, value)
  File "D:\GitStore\Fork_chatgpt_academic\venv\lib\site-packages\urllib3\connection.py", line 224, in putheader
    _HTTPConnection.putheader(self, header, *values)
  File "C:\anaconda3\lib\http\client.py", line 1258, in putheader
    values[i] = one_value.encode('latin-1')
UnicodeEncodeError: 'latin-1' codec can't encode characters in position 10-12: ordinal not in range(256)
```
我觉得可能还是proxy的问题，相当于每一句话都没有回复，都是none，最后也就写不进文件。
只是我现在check_proxy.py没有问题
![image](https://user-images.githubusercontent.com/104243312/228236401-b76875d6-89e1-47fe-878f-7776135d9319.png)
但是在页面中提问就显示timeout
![image](https://user-images.githubusercontent.com/104243312/228236552-c8cfa216-f505-42cf-adb9-83cd858d2368.png)
我再研究研究

**Comment by binary-husky** [comment]
这种情况我只能联想到代理服务器的问题  #41 
另外注意隐藏你的ip地址，暴露了不好

**Comment by topple0610** [comment]
我也是同样的问题。一直是 write argument must be str
终端报错是：
![image](https://user-images.githubusercontent.com/59161752/228252573-e2b889d6-054d-41c9-8970-c069572beeb2.png)

**Comment by ShiJi001** [comment]
我也遇到了你这个问题，然后我尝试设置了代理服务器（原本没有在config里面设置，而是代理软件开全局），并且增加了时间和尝试次数之后就解决了。
`# 发送请求到OpenAI后，等待多久判定为超时
TIMEOUT_SECONDS = 50

# 网页的端口, -1代表随机端口
WEB_PORT = -1

# 如果OpenAI不响应（网络卡顿、代理失败、KEY失效），重试的次数限制
MAX_RETRY = 5`

我怀疑问题的原因是代理网络不稳定。

**Comment by topple0610** [comment]
对的。。增加了响应时间问题就解决了~

**Comment by LiSonglin-xidian** [comment]
你好我clash使用的是全局代理，使用的是美国节点，然后config里面设置proxies = { "http": "127.0.0.1:7890", "https": "127.0.0.1:7890", } 超时判断以及重试次数也改了但是运行python check_proxy.py还是报错
网络代理状态：运行。
代理配置 127.0.0.1:7890, 代理所在地查询超时，代理可能无效
请问这这么改啊~

**Comment by something-19** [comment]
woc，原来是因为config.py中设置API_KEY是在第一句，倒数第二行那里不用改。我说为什么 check_proxy.py通过，直接打开gpt网站没问题，但还是timeout。现在正常啦，参考#60

**Comment by something-19** [comment]
> 你好我clash使用的是全局代理，使用的是美国节点，然后config里面设置proxies = { "http": "127.0.0.1:7890", "https": "127.0.0.1:7890", } 超时判断以及重试次数也改了但是运行python check_proxy.py还是报错 网络代理状态：运行。 代理配置 127.0.0.1:7890, 代理所在地查询超时，代理可能无效 请问这这么改啊~

clash没用过，可以参考 #1 和#9

**Comment by thudjx** [comment]
可以请问一下，大家是怎么给apikey续费的吗？官方不接受中国的信用卡支付，我彻底没招了😂

**Comment by something-19** [comment]
> 可以请问一下，大家是怎么给apikey续费的吗？官方不接受中国的信用卡支付，我彻底没招了😂

一般都是申请虚拟信用卡，通过币平台什么的，网上搜一下gpt api充值教程，充值方式是一样的
