### ISSUE TITLE
Encountered text corresponding to disallowed special token '<|endoftext|>

### ISSUE THREAD

**Issue by netyster** [binary-husky/chatgpt_academic#449]
**Describe the bug 简述**
花了8U。。
**Screen Shot 截图**
![image](https://user-images.githubusercontent.com/65208772/231665489-5c731cb9-7ca8-4ccd-8967-5acedd8583a6.png)

**Terminal Traceback 终端traceback（如果有）**
Traceback (most recent call last):
  File "D:\project\chatgpt_academic-version2.67\crazy_functions\crazy_utils.py", line 186, in _req_gpt
    gpt_say = predict_no_ui_long_connection(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\project\chatgpt_academic-version2.67\request_llm\bridge_chatgpt.py", line 102, in predict_no_ui_long_connection
    raise ConnectionAbortedError("正常结束，但显示Token不足，导致输出不完整，请削减单次输入的文本量。")
ConnectionAbortedError: 正常结束，但显示Token不足，导致输出不完整，请削减单次输入的文本量。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\project\chatgpt_academic-version2.67\toolbox.py", line 185, in decorated
    yield from f(txt, top_p, temperature, chatbot, history, systemPromptTxt, WEB_PORT)
  File "D:\project\chatgpt_academic-version2.67\crazy_functions\解析项目源代码.py", line 127, in 解析一个Python项目
    yield from 解析源代码新(file_manifest, project_folder, llm_kwargs, plugin_kwargs, chatbot, history, system_prompt)
  File "D:\project\chatgpt_academic-version2.67\crazy_functions\解析项目源代码.py", line 28, in 解析源代码新
    gpt_response_collection = yield from request_gpt_model_multi_threads_with_very_awesome_ui_and_high_efficiency(
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\project\chatgpt_academic-version2.67\crazy_functions\crazy_utils.py", line 263, in request_gpt_model_multi_threads_with_very_awesome_ui_and_high_efficiency
    gpt_res = f.result()
              ^^^^^^^^^^
  File "D:\Program Files\python3.11\Lib\concurrent\futures\_base.py", line 449, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "D:\Program Files\python3.11\Lib\concurrent\futures\_base.py", line 401, in __get_result
    raise self._exception
  File "D:\Program Files\python3.11\Lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\project\chatgpt_academic-version2.67\crazy_functions\crazy_utils.py", line 201, in _req_gpt
    inputs, history = input_clipping(inputs, history, max_token_limit=MAX_TOKEN-EXCEED_ALLO)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\project\chatgpt_academic-version2.67\crazy_functions\crazy_utils.py", line 13, in input_clipping
    input_token_num = get_token_num(inputs)
                      ^^^^^^^^^^^^^^^^^^^^^
  File "D:\project\chatgpt_academic-version2.67\crazy_functions\crazy_utils.py", line 9, in get_token_num
    def get_token_num(txt): return len(enc.encode(txt))
                                       ^^^^^^^^^^^^^^^
  File "D:\Program Files\python3.11\Lib\site-packages\tiktoken\core.py", line 117, in encode
    raise_disallowed_special_token(match.group())
  File "D:\Program Files\python3.11\Lib\site-packages\tiktoken\core.py", line 337, in raise_disallowed_special_token
    raise ValueError(
ValueError: Encountered text corresponding to disallowed special token '<|endoftext|>'.
If you want this text to be encoded as a special token, pass it to `allowed_special`, e.g. `allowed_special={'<|endoftext|>', ...}`.
If you want this text to be encoded as normal text, disable the check for this token by passing `disallowed_special=(enc.special_tokens_set - {'<|endoftext|>'})`.
To disable this check for all special tokens, pass `disallowed_special=()`.

Before submitting an issue 提交issue之前：
- Please try to upgrade your code. 如果您的代码不是最新的，建议您先尝试更新代码
- Please check project wiki for common problem solutions.项目[wiki](https://github.com/binary-husky/chatgpt_academic/wiki)有一些常见问题的解决方法

**Comment by binary-husky** [comment]
提供测试样本？

**Comment by binary-husky** [comment]
> https://github.com/NVIDIA/DeepLearningExamples/archive/refs/heads/master.zip

测试中

**Comment by binary-husky** [comment]
![image](https://user-images.githubusercontent.com/96192199/231934109-55a8f122-4fe9-4ca6-a423-9c98edfc83ce.png)
加了一句这个

**Comment by binary-husky** [comment]
然后这个项目怎么有两千多个python文件呀，离谱，一晚上直接把我账号余额吸干了都😂

**Comment by binary-husky** [comment]
@netyster 如果一定要处理这么多文件，最好处理一下这个for循环，比如100个文件为一组，不然真的需要很长很长时间才能执行到`write_results_to_file(report_part_1)`的存档步骤

![image](https://user-images.githubusercontent.com/96192199/231934834-f365be15-e7ab-4387-be22-8ff7f92fa9f1.png)

**Comment by netyster** [comment]
> @netyster 如果一定要处理这么多文件，最好处理一下这个for循环，比如100个文件为一组，不然真的需要很长很长时间才能执行到`write_results_to_file(report_part_1)`的存档步骤
> 
> 
> 
> ![image](https://user-images.githubusercontent.com/96192199/231934834-f365be15-e7ab-4387-be22-8ff7f92fa9f1.png)
> 
> 

好的，谢谢！
