### ISSUE TITLE
环境运行错误

### ISSUE THREAD

**Issue by TongXiaoYang** [binary-husky/chatgpt_academic#461]
TXY@DESKTOP-ABH0DNG MINGW64 ~/chatgpt_academic (master)
$ python check_proxy.py
[PROXY] ▒▒▒▒▒▒▒״̬▒▒▒▒▒▒▒á▒▒▒▒▒▒▒Ϣ▒▒▒£▒ {'https://localhost:7890', 'http://localhost:7890'}
Traceback (most recent call last):
  File "check_proxy.py", line 141, in <module>
    proxies, = get_conf('proxies')
  File "C:\Users\TXY\chatgpt_academic\toolbox.py", line 503, in get_conf
    r = read_single_conf_with_lru_cache(arg)
  File "C:\Users\TXY\chatgpt_academic\toolbox.py", line 495, in read_single_conf_with_lru_cache
    assert isinstance(r, dict), 'proxies▒▒ʽ▒▒▒▒▒▒ע▒▒proxiesѡ▒▒ĸ▒ʽ▒▒▒▒Ҫ▒▒©▒▒▒š▒'
AssertionError: proxies▒▒ʽ▒▒▒▒▒▒ע▒▒proxiesѡ▒▒ĸ▒ʽ▒▒▒▒Ҫ▒▒©▒▒▒š▒

**Comment by binary-husky** [comment]
代理格式写错了
