### ISSUE TITLE
翻译等需要读取本地pdf的功能会产生gbk编码错误

### ISSUE THREAD

**Issue by Sinsgo123** [binary-husky/chatgpt_academic#522]
- **(1) Describe the bug 简述**
在我使用批量翻译pdf文件(多线程)等从本地直接上传的pdf相关的功能时，在解析pdf的时候会出现gbk编码错误

- **(2) Screen Shot 截图**

![bug截图](https://user-images.githubusercontent.com/131123341/232671285-42a50945-9be8-476d-94a2-79198b496647.png)

- **(3) Terminal Traceback 终端traceback（如有）**
Traceback (most recent call last):
  File "F:\ChatGPT\chatgpt_academic\toolbox.py", line 185, in decorated
    yield from f(txt, top_p, temperature, chatbot, history, systemPromptTxt, WEB_PORT)
  File "F:\ChatGPT\chatgpt_academic\crazy_functions\批量翻译PDF文档_多线程.py", line 56, in 批量翻译PDF文档
    yield from 解析PDF(file_manifest, project_folder, llm_kwargs, plugin_kwargs, chatbot, history, sys_prompt)
  File "F:\ChatGPT\chatgpt_academic\crazy_functions\批量翻译PDF文档_多线程.py", line 67, in 解析PDF
    file_content, page_one = read_and_clean_pdf_text(fp)
  File "F:\ChatGPT\chatgpt_academic\crazy_functions\crazy_utils.py", line 558, in read_and_clean_pdf_text
    print亮黄(f)
  File "C:\Python310\lib\site-packages\colorama\ansitowin32.py", line 41, in write
    self.__convertor.write(text)
  File "C:\Python310\lib\site-packages\colorama\ansitowin32.py", line 162, in write
    self.write_and_convert(text)
  File "C:\Python310\lib\site-packages\colorama\ansitowin32.py", line 190, in write_and_convert
    self.write_plain_text(text, cursor, len(text))
  File "C:\Python310\lib\site-packages\colorama\ansitowin32.py", line 195, in write_plain_text
    self.wrapped.write(text[start:end])
UnicodeEncodeError: 'gbk' codec can't encode character '\ufb01' in position 40: illegal multibyte sequence

- **(4) Material to Help Reproduce Bugs 帮助我们复现的测试材料样本（如有）**
其中出错的一个论文地址：https://arxiv.org/pdf/1910.05773.pdf

Before submitting an issue 提交issue之前：
- Please try to upgrade your code. 如果您的代码不是最新的，建议您先尝试更新代码
- Please check project wiki for common problem solutions.项目[wiki](https://github.com/binary-husky/chatgpt_academic/wiki)有一些常见问题的解决方法

**Comment by binary-husky** [comment]
你好，确认为小bug，临时workaround：
- 切换成powershell，vscode等其他终端
- 删除报错的`print`代码，不影响程序的运行
