### ISSUE TITLE
解析c++项目最后阶段报错

### ISSUE THREAD

**Issue by cvt220106** [binary-husky/chatgpt_academic#528]
选择函数功能：解析整个c++项目
**input输入区**：F:\起始的绝对路径
**最终报错信息**：
[Local Message] 实验性函数调用出错:
Traceback (most recent call last):
  File "F:\git_clone\GPT_appliacation\chatgpt_academic\toolbox.py", line 185, in decorated
    yield from f(txt, top_p, temperature, chatbot, history, systemPromptTxt, WEB_PORT)
  File "F:\git_clone\GPT_appliacation\chatgpt_academic\crazy_functions\解析项目源代码.py", line 157, in 解析一个C项目
    yield from 解析源代码新(file_manifest, project_folder, llm_kwargs, plugin_kwargs, chatbot, history, system_prompt)
  File "F:\git_clone\GPT_appliacation\chatgpt_academic\crazy_functions\解析项目源代码.py", line 31, in 解析源代码新
    gpt_response_collection = yield from request_gpt_model_multi_threads_with_very_awesome_ui_and_high_efficiency(
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\git_clone\GPT_appliacation\chatgpt_academic\crazy_functions\crazy_utils.py", line 284, in request_gpt_model_multi_threads_with_very_awesome_ui_and_high_efficiency
    gpt_res = f.result()
              ^^^^^^^^^^
  File "F:\opt\python311\Lib\concurrent\futures\_base.py", line 449, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "F:\opt\python311\Lib\concurrent\futures\_base.py", line 401, in __get_result
    raise self._exception
  File "F:\opt\python311\Lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\git_clone\GPT_appliacation\chatgpt_academic\crazy_functions\crazy_utils.py", line 213, in _req_gpt
    inputs, history = input_clipping(inputs, history, max_token_limit=MAX_TOKEN-EXCEED_ALLO)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\git_clone\GPT_appliacation\chatgpt_academic\crazy_functions\crazy_utils.py", line 7, in input_clipping
    enc = tiktoken.encoding_for_model(*get_conf('LLM_MODEL'))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\opt\python311\Lib\site-packages\tiktoken\model.py", line 75, in encoding_for_model
    return get_encoding(encoding_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\opt\python311\Lib\site-packages\tiktoken\registry.py", line 63, in get_encoding
    enc = Encoding(**constructor())
                     ^^^^^^^^^^^^^
  File "F:\opt\python311\Lib\site-packages\tiktoken_ext\openai_public.py", line 64, in cl100k_base
    mergeable_ranks = load_tiktoken_bpe(
                      ^^^^^^^^^^^^^^^^^^
  File "F:\opt\python311\Lib\site-packages\tiktoken\load.py", line 115, in load_tiktoken_bpe
    return {
           ^
  File "F:\opt\python311\Lib\site-packages\tiktoken\load.py", line 117, in <dictcomp>
    for token, rank in (line.split() for line in contents.splitlines() if line)
        ^^^^^^^^^^^
ValueError: not enough values to unpack (expected 2, got 1)

**Comment by binary-husky** [comment]
版本是？请尝试更新代码

**Comment by binary-husky** [comment]
duplication of #547
