### ISSUE TITLE
更新后报错

### ISSUE THREAD

**Issue by zhdang** [binary-husky/chatgpt_academic#536]
- **(1) Describe the bug 简述**
更新版本后，出现以下报错。

- **(2) Screen Shot 截图**
Traceback (most recent call last):
  File "D:\chatgpt\chatgpt_academic\toolbox.py", line 459, in read_single_conf_with_lru_cache
    r = getattr(importlib.import_module('config_private'), arg)
  File "C:\ProgramData\anaconda3\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'config_private'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\chatgpt\chatgpt_academic\main.py", line 189, in <module>
    main()
  File "D:\chatgpt\chatgpt_academic\main.py", line 9, in main
    get_conf('proxies', 'WEB_PORT', 'LLM_MODEL', 'CONCURRENT_COUNT', 'AUTHENTICATION', 'CHATBOT_HEIGHT', 'LAYOUT', 'API_KEY', 'AVAIL_LLM_MODELS')
  File "D:\chatgpt\chatgpt_academic\toolbox.py", line 481, in get_conf
    r = read_single_conf_with_lru_cache(arg)
  File "D:\chatgpt\chatgpt_academic\toolbox.py", line 461, in read_single_conf_with_lru_cache
    r = getattr(importlib.import_module('config'), arg)
AttributeError: module 'config' has no attribute 'AVAIL_LLM_MODELS'

**Comment by zhdang** [comment]
收到，谢谢。重新装了下，问题解决了------------------------------------------------------------------
***@***.***>
日　期：2023年04月19日 21:26:48
***@***.***>
***@***.***>; ***@***.***>
主　题：Re: [binary-husky/chatgpt_academic] 更新后报错 (Issue #536)

Closed #536 as completed.
