### ISSUE TITLE
批量翻译PDF文档(多线程) ValueError not enough values to unpack (expected 2, got 1)

### ISSUE THREAD

**Issue by Alethiea-Cheng** [binary-husky/chatgpt_academic#551]
- **(1) Describe the bug 简述**
chatgpt_academic：2.7、3.1
Windows 64bit教育版
終端：(anaconda)cmd -> python
python 3.11.3

parsing PDF時出現參數數量不匹配，並非所有電腦會出現bug

- **(2) Screen Shot 截图**

- **(3) Terminal Traceback 终端traceback（如有）**
我上传了文件，请查收

[Local Message] 收到以下文件:

private_upload\2023-04-21-03-25-48

private_upload\2023-04-21-03-25-48\gemmini-arxiv-1911.09925.pdf

调用路径参数已自动修正到:

private_upload/2023-04-21-03-25-48

现在您点击任意“红颜色”标识的函数插件时，以上文件将被作为输入参数

函数插件功能？

[Local Message] 实验性函数调用出错:

Traceback (most recent call last):
  File "C:\chatgpt_academic2.7\chatgpt_academic\toolbox.py", line 185, in decorated
    yield from f(txt, top_p, temperature, chatbot, history, systemPromptTxt, WEB_PORT)
  File "C:\chatgpt_academic2.7\chatgpt_academic\crazy_functions\批量翻译PDF文档_多线程.py", line 56, in 批量翻译PDF文档
    yield from 解析PDF(file_manifest, project_folder, llm_kwargs, plugin_kwargs, chatbot, history, sys_prompt)
  File "C:\chatgpt_academic2.7\chatgpt_academic\crazy_functions\批量翻译PDF文档_多线程.py", line 72, in 解析PDF
    enc = tiktoken.encoding_for_model(*get_conf('LLM_MODEL'))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\wen\anaconda3\envs\ac\Lib\site-packages\tiktoken\model.py", line 75, in encoding_for_model
    return get_encoding(encoding_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\wen\anaconda3\envs\ac\Lib\site-packages\tiktoken\registry.py", line 63, in get_encoding
    enc = Encoding(**constructor())
                     ^^^^^^^^^^^^^
  File "C:\Users\wen\anaconda3\envs\ac\Lib\site-packages\tiktoken_ext\openai_public.py", line 64, in cl100k_base
    mergeable_ranks = load_tiktoken_bpe(
                      ^^^^^^^^^^^^^^^^^^
  File "C:\Users\wen\anaconda3\envs\ac\Lib\site-packages\tiktoken\load.py", line 115, in load_tiktoken_bpe
    return {
           ^
  File "C:\Users\wen\anaconda3\envs\ac\Lib\site-packages\tiktoken\load.py", line 117, in <dictcomp>
    for token, rank in (line.split() for line in contents.splitlines() if line)
        ^^^^^^^^^^^
ValueError: not enough values to unpack (expected 2, got 1)
当前代理可用性:

代理配置 无, 代理所在地：未知，IP查询频率受限

- **(4) Material to Help Reproduce Bugs 帮助我们复现的测试材料样本（如有）**
手邊有的電腦中，僅有某一電腦出現此問題，任一篇論文均可復現此bug

Before submitting an issue 提交issue之前：
- Please try to upgrade your code. 如果您的代码不是最新的，建议您先尝试更新代码
- Please check project wiki for common problem solutions.项目[wiki](https://github.com/binary-husky/chatgpt_academic/wiki)有一些常见问题的解决方法

**Comment by Alethiea-Cheng** [comment]
理解PDF文档内容 也出現了相同問題
函数插件功能？

[Local Message] 实验性函数调用出错:

Traceback (most recent call last):
  File "C:\chatgpt_academic2.7\chatgpt_academic\toolbox.py", line 185, in decorated
    yield from f(txt, top_p, temperature, chatbot, history, systemPromptTxt, WEB_PORT)
  File "C:\chatgpt_academic2.7\chatgpt_academic\crazy_functions\理解PDF文档内容.py", line 112, in 理解PDF文档内容标准文件输入
    yield from 解析PDF(txt, llm_kwargs, plugin_kwargs, chatbot, history, system_prompt)
  File "C:\chatgpt_academic2.7\chatgpt_academic\crazy_functions\理解PDF文档内容.py", line 21, in 解析PDF
    enc = tiktoken.encoding_for_model(*get_conf('LLM_MODEL'))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\wen\anaconda3\envs\ac\Lib\site-packages\tiktoken\model.py", line 75, in encoding_for_model
    return get_encoding(encoding_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\wen\anaconda3\envs\ac\Lib\site-packages\tiktoken\registry.py", line 63, in get_encoding
    enc = Encoding(**constructor())
                     ^^^^^^^^^^^^^
  File "C:\Users\wen\anaconda3\envs\ac\Lib\site-packages\tiktoken_ext\openai_public.py", line 64, in cl100k_base
    mergeable_ranks = load_tiktoken_bpe(
                      ^^^^^^^^^^^^^^^^^^
  File "C:\Users\wen\anaconda3\envs\ac\Lib\site-packages\tiktoken\load.py", line 115, in load_tiktoken_bpe
    return {
           ^
  File "C:\Users\wen\anaconda3\envs\ac\Lib\site-packages\tiktoken\load.py", line 117, in <dictcomp>
    for token, rank in (line.split() for line in contents.splitlines() if line)
        ^^^^^^^^^^^
ValueError: not enough values to unpack (expected 2, got 1)
当前代理可用性:

代理配置 无, 代理所在地：未知，IP查询频率受限

**Comment by binary-husky** [comment]
很可能tiktoken版本不正确

**Comment by binary-husky** [comment]
另外我看到代码版本不是最新的

**Comment by binary-husky** [comment]
https://qiita.com/KONTA2019/items/8ec10b8bf4dfca3bfb75

**Comment by binary-husky** [comment]
duplication of #547
