### ISSUE TITLE
请问出现8K context error怎么解决

### ISSUE THREAD

**Issue by Yujia-lab** [binary-husky/chatgpt_academic#563]
刚刚下载下来还好好的，手残忘了是不是改错了某个参数。点提交就一直报这个错，用的是海外网络应该不存在vpn的问题。

Traceback (most recent call last):
  File "/Users/yujia/opt/anaconda3/envs/chatgpt/lib/python3.9/site-packages/gradio/routes.py", line 401, in run_predict
    output = await app.get_blocks().process_api(
  File "/Users/yujia/opt/anaconda3/envs/chatgpt/lib/python3.9/site-packages/gradio/blocks.py", line 1302, in process_api
    result = await self.call_function(
  File "/Users/yujia/opt/anaconda3/envs/chatgpt/lib/python3.9/site-packages/gradio/blocks.py", line 1039, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "/Users/yujia/opt/anaconda3/envs/chatgpt/lib/python3.9/site-packages/anyio/to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/Users/yujia/opt/anaconda3/envs/chatgpt/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "/Users/yujia/opt/anaconda3/envs/chatgpt/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "/Users/yujia/opt/anaconda3/envs/chatgpt/lib/python3.9/site-packages/gradio/utils.py", line 491, in async_iteration
    return next(iterator)
  File "/Users/yujia/Data/Code/chatgpt_academic-master/toolbox.py", line 47, in decorated
    yield from f(txt_passon, llm_kwargs, plugin_kwargs, chatbot_with_cookie, history, system_prompt, *args)
  File "/Users/yujia/Data/Code/chatgpt_academic-master/request_llm/bridge_all.py", line 228, in predict
    method = model_info[llm_kwargs['llm_model']]["fn_with_ui"]
KeyError: '8K context'

**Comment by binary-husky** [comment]
检查`config.py`吧😂
