### ISSUE TITLE
为什么提示json解析错误

### ISSUE THREAD

**Issue by xufengnian-bei** [binary-husky/chatgpt_academic#81]
[Local Message] Json Error

Traceback (most recent call last):

File "c:\Users\wsw\Desktop\chatgpt_academic-master\chatgpt_academic-master\predict.py", line 114, in predict

if len(json.loads(chunk.decode()[6:])['choices'][0]["delta"]) == 0:
File "D:\anaconda\lib\json__init__.py", line 346, in loads

return _default_decoder.decode(s)
File "D:\anaconda\lib\json\decoder.py", line 337, in decode

obj, end = self.raw_decode(s, idx=_w(s, 0).end())
File "D:\anaconda\lib\json\decoder.py", line 355, in raw_decode

raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

"error": { "message": "You exceeded your current quota, please check your plan and billing details.", "type": "insufficient_quota", "param": null, "code": null }}

**Comment by Jonathanyu2014** [comment]
同问
